name: mayavi_test
dependencies:
- apptools=4.2.1
- configobj=5.0.6
- envisage=4.4.0
- jpeg=8d
- libpng=1.6.17
- libtiff=4.0.6
- mayavi=4.4.0
- numpy=1.9.3
- openssl=1.0.2h
- pip=8.1.1=py27_1
- pyface=4.4.0
- pyqt>=4.11.4
- python>=2.7.11
- qt>=4.8.7
- setuptools=21.2.1
- sip=4.16.9
- six=1.10.0
- traits=4.4.0
- traitsui=4.4.0
- vtk=5.10.1
- wheel=0.29.0
- zlib=1.2.8

